name: Auto Merge

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'automerge'
    steps:
      - uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
